export const ADD_TO_AGENDA = "ADD_TO_AGENDA";
export const REMOVE_FROM_AGENDA = "REMOVE_FROM_AGENDA";
export const UPDATE_NOTIFICATIONS = "UPDATE_NOTIFICATIONS";

export const ADD_TO_MY_EVENTS = "ADD_TO_MY_EVENTS";
export const REMOVE_FROM_MY_EVENTS = "REMOVE_FROM_MY_EVENTS";

export const UPDATE_SESSION_NOTES = "UPDATE_SESSION_NOTES";
